[project]
name = "NuMojo"
version = "0.2.0"
description = "NuMojo is a library for numerical computing written in Mojo 🔥"
authors = [
    "Shivasankar <shivasankar.ka@gmail.com>",
    "MadAlex1997 <>",
    "Yuhao Zhu <>",
    "mmenendezg <>",
    "sandstromviktor <>",
]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["osx-arm64", "linux-64"]
license = "Apache-2.0"

[tasks]
# test whether tests pass and the package can be built
test = " magic run mojo test tests -I ./ && magic run mojo package numojo"
package = "magic run mojo package numojo"
# runs all final checks before a commit
final = "magic run mojo test tests -I ./ && magic run mojo format ./ && magic run mojo package numojo"

[dependencies]
max = ">=24.4.0,<25"
